let letraInicialPais = "a";
let chatMsjReunion = "hola";
let pesoBotellaLitro ="1";
let estadoServicio = true;
let nombreCentroFormacion ="cfp27";
let contraseniaYoutube = '1!._.-,asf_falxse';
let numeroCelular = "1159129432";
let nombrePostre = "flan";
let claveProducto ="123N-976G-54F";